development:
  adapter: postgresql
  encoding: unicode
  database: cms_development
  pool: 5
  username: sergei
  password:

test: &TEST
  adapter: postgresql
  encoding: unicode
  database: cms_test
  pool: 5
  username: sergei
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: cms_production
  pool: 5
  username: sergei
  password:

cucumber:
  <<: *TEST
