# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 278881f87475b7de1a9cc90ba214b334b258128a071df94c89d18dd5aa60a94ac44083d0028d871286dd3f10b3e98805883083a8e004443ad8a76ece51f8fb88

test:
  secret_key_base: 5a8897d6582f3dc9f680b3921eba4563f37af633c3cee88ea5b1bed153dc673a66cad4c697f978ab0221509eb40df346fb9ebde2e32607ed960bc43031b865a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
